//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OT.Ternium.NVA.EstructuraClinicas.Models.Help
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<spCatPersonalByIdNM_Select_Result> spCatPersonalByIdNM_Select(Nullable<int> idPersonal)
        {
            var idPersonalParameter = idPersonal.HasValue ?
                new ObjectParameter("IdPersonal", idPersonal) :
                new ObjectParameter("IdPersonal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCatPersonalByIdNM_Select_Result>("spCatPersonalByIdNM_Select", idPersonalParameter);
        }
    }
}
